Remove sonar as subdomain source
edoardottt/scilla pull request #115
Opened 2023-10-12 21:42 UTC by carlosfrodrigues

closes #113

2023-10-13 05:44 UTC, edoardottt requested changes

2023-10-13 05:44 UTC, edoardottt commented on pkg/runner/runner.go
> -		sonar := opendb.SonarSubdomains(urlUtils.CleanProtocol(target), false)
Can you please comment these two lines instead of deleting them? Just comment them and add a comment saying `service not working`

2023-10-13 05:44 UTC, edoardottt commented on pkg/runner/runner.go
> -		sonar := opendb.SonarSubdomains(urlUtils.CleanProtocol(target), userInput.SubdomainPlain)
Same here

2023-10-13 23:04 UTC, carlosfrodrigues commented
Changes done! :)

2023-10-14 07:12 UTC, edoardottt approved these changes
lgtm

2023-10-14 07:15 UTC, merged