feature: adding subdomain center as source
edoardottt/scilla pull request #118
Opened 2023-10-16 19:49 UTC by iamshreeram

This source returns the empty list for almost all the domains. The original [sourcecode](https://github.com/owasp-amass/amass/blob/5f1f7176bae60975c1e5be64273cb201f1bb37c3/resources/scripts/api/subdomaincenter.ads) has rate limiting (upto 2 request) as well.

2023-10-17 05:49 UTC, edoardottt requested changes

2023-10-17 05:49 UTC, edoardottt commented on pkg/opendb/subdomaincenter.go
> +		fmt.Println("Pulling data from ThreatCrowd")
It's not threatcrowd

2023-10-17 05:49 UTC, edoardottt commented on pkg/opendb/subdomaincenter.go
> +	err = dec.Decode(&wrapper)
Here trying this code I get the err `json: cannot unmarshal array into Go value of type struct { Records []string "json:\"subdomains\"" }`

2023-10-18 00:40 UTC, iamshreeram commented
@edoardottt , Please look into [5217aa6](https://github.com/edoardottt/scilla/pull/118/commits/5217aa68f909e3c66f0a3061900a4b1bbdb9447c)

2023-10-18 07:35 UTC, edoardottt requested changes

2023-10-18 07:35 UTC, edoardottt commented on pkg/opendb/subdomaincenter.go
> +		fmt.Println("Pulling data from Subdomain")
Should be `Pulling data from Subdomain Center`

2023-10-18 12:04 UTC, iamshreeram commented
1. Sure. Thanks!
2. I have added the code to main enumeration, both in `ReportSubcommandHandler` and `SubdomainSubcommandHandler`
3. I have fixed the linting problem. 

Please review - #[df98dcc](https://github.com/edoardottt/scilla/pull/118/commits/df98dccc464a9add624e895720dc09e432b75ba4)

2023-10-18 12:13 UTC, edoardottt approved these changes
lgtm

2023-10-18 12:13 UTC, merged